### PR TITLE
add `provides` and `makedepends`

### PR DESCRIPTION
**Pull request by goekce**
I am working on other packages. Then I could add `ros2` as a dependency.

### CODE REVIEW

**Comment by m2-farzan** [comment]
Can you please update this PR with the following changes before I merge it?

1. Increment `pkgrel` value. The value is used by pacman and AUR helpers so that they know if a package has been changed since the last time they visited it.
2. Run the command `makepkg --printsrcinfo > .SRCINFO`. This will update .SRCINFO file used by AUR. (The pkgver might change as a side effect but that's fine)

More info on these can be found on arch wiki.

**Comment by goekce** [comment]
Sorry Mostafa, I will pay attention next time!

**Comment by m2-farzan** [comment]
Thanks! No worries, I often forget to bump pkgrel and srcinfo too...

By the way, since you're developing other ros2 pkgbuilds, I invite you to check out my other repo https://github.com/m2-farzan/ros2-supplementary-pkgbuilds. It's still work in progress but it aims to provide an all-in-one package for common ros2 packages. I'd be happy to collaborate if your goals have overlap with my attempt in that repo.

**Comment by goekce** [comment]
Great, I am trying to compile packages for Turtlebot3 too! I like your approach of creating the commonly used packages as an overlay to the desktop image.

In last days I tried to integrate `rosinstall_generator` into PKGBUILD with recursive deps for galactic, but still have some errors. I will let you know.

**Comment by goekce** [comment]
I tried to get a list of repositories using `rosinstall_generator` and put them into the `source` array. The advantage is that now the PKGBUILD uses the `makepkg` vcs pulling features instead of `vcs`. On the other hand the PKGBUILD takes now more time than `vcs import` because one repository can contain many ROS packages. For example if a ROS repo contains seven ROS packages, then `makepkg` clones seven times the same repository.

I mirrored my repo to https://github.com/goekce/pkgbuilds

The PKGBUILDs which use the above method are:

- https://github.com/goekce/pkgbuilds/tree/main/ros-galactic-turtlebot3-quickstart
- https://github.com/goekce/pkgbuilds/tree/main/ros-galactic-turtlebot3-robot-quickstart

I do not know if PKGBUILDs were designed to be misused like normal shell scripts, but the code could still be used to generate other PKGBUILDs dynamically.

Some changes I remember are:

- use `ros-galactic` instead of `ros2-*, because Ubuntu packages use the same naming
- removed the RAM check, because it looks complex and I mostly compile arm packages on a powerful computer in chroot

Thanks for your work MM :)

**Comment by m2-farzan** [comment]
That's an interesting approach. Thanks for sharing!

**Pull request merged**
